name: app_poezdka
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter     

  #parse server
  parse_server_sdk_flutter: ^3.1.3
  #UI
  dropdown_button2: ^1.6.2
  flutter_vector_icons: ^1.0.0
  modal_bottom_sheet: ^2.0.1
  smooth_page_indicator: ^1.0.0+2
  persistent_bottom_nav_bar_v2: ^4.2.3
  flutter_smart_dialog: ^4.5.3+2
  flutter_svg: ^1.1.1
  keyboard_actions: ^4.0.1
  syncfusion_flutter_sliders: ^20.2.36
  dash_chat_2: ^0.0.11
  #Geolocator
  geolocator: ^9.0.1
  http: ^0.13.4
  dio: ^4.0.6
  url_launcher: ^6.1.5
  cached_network_image: ^3.2.1
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^6.1.0
  shared_preferences: ^2.0.15
  hive: ^2.2.2
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  ### Temorary packages
  drift: ^2.3.0
  uuid: ^3.0.6
  scale_button: ^2.1.2
  #Firebase
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  firebase_analytics: ^10.0.6
  firebase_messaging: ^14.1.3
  firebase_dynamic_links: ^5.0.7
  #Rating
  flutter_rating_bar: ^4.0.1
  #WebView
  webview_flutter: ^3.0.4
  #Vibration
  vibration: ^1.7.5
  flutter_login_vk: ^2.2.1
  image_picker: ^0.8.5+3
  #Google
  google_maps_flutter: ^2.1.11
  flutter_polyline_points: ^1.0.0
  flutter_image_compress: ^1.1.1
  google_sign_in: ^5.4.1
  sign_in_with_apple: ^4.1.0
  apple_sign_in_safety: ^0.0.6
  pinput: ^2.2.12
  masked_text_field: ^1.0.1
  uni_links: ^0.5.1
  #share
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.3.2
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/city/
    - assets/car/
    - assets/phone/
    - assets/icon/
